# Generated by Django 4.0.1 on 2022-03-18 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
    ]
